name: internet-health-monitor
schedule: "@daily"
start_date: "2026-04-01"

default_connections:
  duckdb: "duckdb-default"

tags: [ "daily", "internet-health", "isoc-pulse" ]
domains: [ "infrastructure", "security" ]
owner: data-platform

catchup: true
concurrency: 4
max_active_steps: 8

default:
  rerun_cooldown: 300

variables:
  countries:
    type: array
    items:
      type: string
    default:
      - "AE"
      - "AU"
      - "BE"
      - "BR"
      - "CA"
      - "CH"
      - "CN"
      - "DE"
      - "DK"
      - "DZ"
      - "ES"
      - "FI"
      - "FR"
      - "GB"
      - "HR"
      - "ID"
      - "IN"
      - "IT"
      - "JP"
      - "LU"
      - "MA"
      - "NL"
      - "NO"
      - "PT"
      - "QA"
      - "RU"
      - "SA"
      - "SE"
      - "TN"
      - "US"
      - "ZA"
      - "DZ"